[package]
name = "parst"
version = "0.1.2"
edition = "2021"
description = "declarative parsing"
license = "MIT OR Apache-2.0"

[dependencies]
parst_derive = "0.1.1"
memchr = "2.4.1"
thiserror = "1.0.30"
