[package]
name = "parst"
version = "0.1.3"
edition = "2021"
description = "declarative parsing"
license = "MIT OR Apache-2.0"

[dependencies]
memchr = "2.4.1"
thiserror = "1.0.30"
parst_derive = { version = "0.1.1", optional = true }

[features]
default = ["derive"]
derive = ["parst_derive"]