[package]
name = "parst_derive"
version = "0.2.0"
edition = "2021"
description = "derive macros for parst"
license = "MIT OR Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = { version = "2.0.70", features = ["full", "extra-traits"] }
